config/routes.rb
Rails.application.routes.draw do
  get "auth/register"
  get "auth/login"
  get "static_pages/home"
  get "static_pages/help"
  get "render/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "dashboard#index"
  get "dashboard/index"

  get "pokemon/new"
  post "pokemon/create"
  get "pokemon/:id/edit", to: "pokemon#edit"
  patch "pokemon/:id", to: "pokemon#update"

  get "/profile", to: "users#show"
  get "/profile/edit", to: "users#edit"
  patch "/profile", to: "users#update"
  get "/profile/edit_credentials", to: "users#edit_credentials"
  patch "/profile/edit_credentials", to: "users#update_credentials"

  get    "/login",  to: "sessions#new"
  post   "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/register", to: "users#new"
  post "/register", to: "users#create"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :daycare_slots
  has_many :pokemons
  has_one_attached :avatar

  validates :username, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, if: :password_digest_changed?
  validates :bio, length: { maximum: 500 }, allow_blank: true
  validates :avatar, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg']
  before_save { self.email = email.downcase }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "auth", only: [ :new ]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    logger.debug "User params: #{user_params.inspect}"

    if @user.save
      logger.debug "User saved successfully: #{@user.inspect}"
      redirect_to login_path
    else
      logger.debug "User save failed: #{@user.errors.full_messages.inspect}"
      render :new
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def edit_credentials
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_profile_information_params)
      redirect_to profile_path, notice: "Profile updated successfully."
    else
      Rails.logger.debug(@user.errors.full_messages) 
      flash.now[:alert] = @user.errors.full_messages.join(", ")
      render :edit, alert: "Failed to update profile."
    end
  end

  def update_credentials
    @user = current_user
    if @user.authenticate(user_profile_credentials_params[:password])
      if @user.update(user_profile_credentials_params)
        redirect_to profile_path, notice: "Credentials updated successfully."
      else
        Rails.logger.debug(@user.errors.full_messages) 
        flash.now[:alert] = @user.errors.full_messages.join(", ")
        render :edit, alert: "Failed to update credentials."
      end
    else
      flash.now[:alert] = "Current password is incorrect."
      render :edit
    end
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def user_profile_information_params
    params.require(:user).permit(:username, :bio, :avatar)
  end

  def user_profile_credentials_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% content_for :title, "Edit Profile Details" %>
<% content_for :page_title, "Edit Profile Details" %>

<%= render_form_for(@user, url: profile_path, method: :patch, local: true) do |form| %>
  <div class="boxed">
      <div>
        <h1 class="text-lg font-semibold mb-1">Edit Profile Information</h1>
        <p class="text-muted-foreground">
          Update your profile information below.
        </p>
      </div>
      <div class="grid grid-cols-2 gap-4">
        <!-- Avatar Field -->
        <div class="flex flex-col gap-2">
          <p class="font-semibold">Avatar:</p>
          <div class="flex gap-6 items-center">
            <% if @user.avatar.attached? %>
              <%= image_tag @user.avatar, alt: "Avatar Image", class: "size-24 rounded-full text-center object-cover" %>
            <% else %>
              <%= image_tag "default_avatar.jpg", alt: "Avatar Image", class: "size-24 rounded-full text-center object-cover" %>
            <% end %>
            <%= form.file_field  :avatar, class: "input-styled"%>
          </div>
        </div>
        <div class="flex flex-col gap-2">
          <%= form.label :bio, class: "required" %>
          <%= form.text_area :bio, class: "" %>
        </div>
        <div class="flex flex-col gap-2 mb-4">
          <%= form.label :username, class: "required" %>
          <%= form.text_field :username, class: "" %>
        </div>
      </div>
      <div class="flex gap-4">
        <%= render_button "Back", as: :link, href: "/profile", variant: "secondary" %>
        <%= form.submit "Save profile details" %>
      </div>
  </div>
<% end %>

app/views/users/edit_credentials.html.erb
<% content_for :title, "Edit Account Credentials" %>
<% content_for :page_title, "Edit Account Credentials" %>

<%= render_form_for(@user, url: profile_path, method: :patch, local: true) do |form| %>
  <div class="boxed">
    <div>
      <h1 class="text-lg font-semibold mb-1">Account Crendentials</h1>
      <p class="text-muted-foreground">
        This is your chance to update your account credentials.
      </p>
    </div>
    <div class="grid grid-cols-2 gap-4">
      <div class="flex flex-col gap-2 mb-4">
        <%= form.label :email, class: "required" %>
        <%= form.text_field :email, class: "" %>
      </div>
            <div>
      </div>
      <div class="flex flex-col gap-2">
        <%= form.label :password, class: "required" %>
        <%= form.password_field :password, class: "mb-8" %>
      </div>
      <div class="flex flex-col gap-2">
        <%= form.label :password_confirmation, class: "required" %>
        <%= form.password_field :password_confirmation, class: "mb-8" %>
      </div>
    </div>
    <div class="flex gap-4">
      <%= render_button "Back", as: :link, href: "/profile", variant: "secondary" %>
      <%= form.submit "Save account credentials" %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="bg-slate-100 p-6 w-full rounded-md drop-shadow-md">
  <p class="text-xl font-semibold mb-6 text-center">Create a new account</p>
  <%= render_form_with(model: @user, url: register_path, class: "w-full") do |form| %>
      <div class="flex flex-col gap-2 mb-4">
      <%= form.label :username, class: "required" %>
      <%= form.text_field :username, class: "" %>
    </div>
    <div class="flex flex-col gap-2 mb-4">
      <%= form.label :email, class: "required" %>
      <%= form.text_field :email, class: "co" %>
    </div>
    <div class="flex flex-col gap-2">
      <%= form.label :password, class: "required" %>
      <%= form.password_field :password, class: "mb-8" %>
    </div>
    <div class="flex flex-col gap-2">
      <%= form.label :password_confirmation, class: "required" %>
      <%= form.password_field :password_confirmation, class: "mb-8" %>
    </div>
    <div class="flex justify-end items-center gap-4">
      <p class="text-sm text-muted-foreground">Already have an account? <%= link_to "Log in", login_path, class:"underline hover:font-bold" %></p>
      <%= form.submit "Register" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<% content_for :title, "Profile" %>
<% content_for :page_title, "Profile" %>

<div class="boxed">
  <div>
    <h1 class="text-lg font-semibold mb-1">Profile Information</h1>
    <p class="text-muted-foreground">
      This is where you can view and update your profile information.
    </p>
  </div>
  <div class="grid grid-cols-2 gap-4">
    <div class="flex flex-col gap-2">
      <p class="font-semibold">Avatar:</p>
      <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar, alt: "Avatar Image", class: "size-24 rounded-full text-center object-cover" %>
      <% else %>
        <%= image_tag "default_avatar.jpg", alt: "Avatar Image", class: "size-24 rounded-full text-center object-cover" %>
      <% end %>
    </div>
    <div class="flex flex-col gap-2">
      <p class="font-semibold">Bio:</p>
      <p>
        <%= current_user.bio %>
      </p>
    </div>
    <div class="flex flex-col gap-2">
      <p class="font-semibold">Username:</p>
      <p><%= current_user.username %></p>
    </div>
  </div>
  <div>
    <%= render_button "Edit profile details", as: :link, href: "/profile/edit" %>
  </div>
</div>

<div class="boxed">
  <div>
    <h1 class="text-lg font-semibold mb-1">Account Crendentials</h1>
    <p class="text-muted-foreground">
      This is where you can view and update your account credentials.
    </p>
  </div>
  <div class="grid grid-cols-2 gap-4">
    <div class="flex flex-col gap-2">
      <p class="font-semibold">Email:</p>
      <p><%= current_user.email %></p>
    </div>
    <div class="flex flex-col gap-2">
      <p class="font-semibold">Password:</p>
      <p>********</p>
    </div>
  </div>
  <div>
    <%= render_button "Edit account credentials", as: :link, href: "/profile/edit_credentials" %>
  </div>
</div>