config/routes.rb
Rails.application.routes.draw do
  get "auth/register"
  get "auth/login"
  get "static_pages/home"
  get "static_pages/help"
  get "render/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "dashboard#index"
  get "dashboard/index"

  get "pokemon/new"
  post "pokemon/create"
  get "pokemon/:id/edit", to: "pokemon#edit"
  patch "pokemon/:id", to: "pokemon#update"

  get "/profile", to: "users#show"
  get "/profile/edit", to: "users#edit"
  patch "/profile", to: "users#update"
  get "/profile/edit_credentials", to: "users#edit_credentials"
  patch "/profile/edit_credentials", to: "users#update_credentials"

  get    "/login",  to: "sessions#new"
  post   "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/register", to: "users#new"
  post "/register", to: "users#create"
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :user
  has_one :daycare_slot
  has_one_attached :image

  enum :pokemon_type, {
    normal: 0,
    fire: 1,
    water: 2,
    grass: 3,
    electric: 4,
    ice: 5,
    fighting: 6,
    poison: 7,
    ground: 8,
    flying: 9,
    psychic: 10,
    bug: 11,
    rock: 12,
    ghost: 13,
    dragon: 14,
    dark: 15,
    steel: 16,
    fairy: 17,
  }

  validates :name, presence: true, length: { maximum: 50 }
  validates :pokemon_type, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :image, attached: true, content_type: [ "image/png", "image/jpg", "image/jpeg" ]
end

app/controllers/pokemon_controller.rb
class PokemonController < ApplicationController
  def new
    @pokemon = Pokemon.new
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)

    if @pokemon.save
      redirect_to index_path
    else
      render :new
    end
  end

  def edit
    @pokemon = Pokemon.find(params[:id])
  end

  def update
    @pokemon = Pokemon.find(params[:id])

    if @pokemon.update(pokemon_params)
      redirect_to index_path, notice: "Pokemon updated successfully."
    else
      flash.now[:alert] = @pokemon.errors.full_messages.join(", ")
      render :edit, alert: "Failed to update pokemon."
    end
  end
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/views/pokemon/new.html.erb
<% content_for :title, "Register Pokemon" %>
<% content_for :page_title, "Register Pokemon" %>

<%= render_form_for(@pokemon, url: pokemon_create_path, local: true) do |form| %>
  <div class="boxed">
    <div>
      <h1 class="text-lg font-semibold mb-1">Register a new Pokemon</h1>
      <p class="text-muted-foreground">
        Register a new Pokemon below.
      </p>
    </div>
    <div class="grid grid-cols-2 gap-4">
        <!-- Image Field -->
      <div class="flex flex-col gap-2">
        <p class="font-semibold">Image:</p>
        <div class="flex gap-6 items-center">
          <% if @pokemon.image.attached? %>
            <%= image_tag @pokemon.image, alt: "Pokemon Image", class: "size-24 rounded-full text-center object-cover" %>
          <% else %>
            <%= image_tag "default_avatar.jpg", alt: "Pokemon Image", class: "size-24 rounded-full text-center object-cover" %>
          <% end %>
          <%= form.file_field :image, class: "input-styled" %>
        </div>
      </div>
      <!-- Name Field -->
      <div class="flex flex-col gap-2 mb-4">
        <%= form.label :name, class: "required" %>
        <%= form.text_field :name, class: "" %>
      </div>
      <!-- Pokemon Type Field -->
      <div class="flex flex-col gap-2 mb-4">
        <%= form.label :pokemon_type, class: "required" %>
        <%= render_select name: "pokemon[pokemon_type]", selected: @pokemon.pokemon_type do |select| %>
          <% Pokemon.pokemon_types.each do |type, _value| %>
            <%= select.option label: type.capitalize, value: type %>
          <% end %>
        <% end %>
      </div>
      <!-- Description Field -->
      <div class="flex flex-col gap-2">
        <%= form.label :description, class: "required" %>
        <%= form.text_area :description, class: "" %>
      </div>
    </div>
    <div class="flex gap-4">
      <%= render_button "Back", as: :link, href: "/profile", variant: "secondary" %>
      <%= form.submit "Save Pokemon" %>
    </div>
  </div>
<% end %>