config/routes.rb
Rails.application.routes.draw do
  get "auth/register"
  get "auth/login"
  get "static_pages/home"
  get "static_pages/help"
  get "render/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "dashboard#index"
  get "dashboard/index"

  get "pokemon/new"
  post "pokemon/create"
  get "pokemon/:id/edit", to: "pokemon#edit"
  patch "pokemon/:id", to: "pokemon#update"

  get "/profile", to: "users#show"
  get "/profile/edit", to: "users#edit"
  patch "/profile", to: "users#update"
  get "/profile/edit_credentials", to: "users#edit_credentials"
  patch "/profile/edit_credentials", to: "users#update_credentials"

  get    "/login",  to: "sessions#new"
  post   "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/register", to: "users#new"
  post "/register", to: "users#create"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) + " | Poke Daycare" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# Navbar - Move to component folder once completed %>
    <div class="px-8 py-6 bg-background">
      <div class="max-w-screen-xl mx-auto flex justify-between items-center z-10">
        <%= link_to root_path, class: "flex items-center gap-2" do %>
          <%= image_tag "pokeball.png", class: 'w-6' %>
          <p class="text-xl font-semibold cursor-pointer">Poke Daycare</p>
        <% end %>
        <div class="flex gap-6 font-semibold">
          <%= link_to "Home", root_path, class: "hover:border-b border-b-foreground cursor-pointer px-2" %>
          <%= link_to "Profile", profile_path, class: "hover:border-b border-b-foreground cursor-pointer px-2" %>
          <%= button_to "Log out", logout_path, method: :delete, class: "hover:border-b border-b-foreground cursor-pointer px-2" %>
        </div>
      </div>
    </div>

    <div class="py-4 px-8 bg-background border-y drop-shadow-sm">
      <p class="max-w-screen-xl mx-auto text-lg font-semibold"><%= content_for?(:page_title) ? yield(:page_title) : "Page" %></p>
    </div>

    <%# Main Content %>
    <main class="py-10 px-8">
      <div class="max-w-screen-xl mx-auto">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sample App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="bg-slate-200 w-full min-h-screen flex justify-center items-center">
      <div class="flex flex-col max-w-lg w-full items-center gap-4">
        <%= image_tag "pokeball.png", class:'w-20' %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>